name: lauetoolsnn
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - tqdm
  - scikit-image
  - fabio
  - scikit-learn
  - tensorflow
  - h5py
  - keras
  - networkx
  - pyqt
  - matplotlib-base
  - scipy
  - numpy
  - pip
  - setuptools
  - setuptools_scm
  - pip:
    - file:.
