{% set name = "lauetoolsnn" %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  entry_points:
    - lauetoolsnn=lauetoolsnn.lauetoolsneuralnetwork:start
    - lauenn=lauetoolsnn.lauetoolsneuralnetwork:start
    - lauenn_addmat=lauetoolsnn.util_scripts.add_material:start
    - lauenn_mat=lauetoolsnn.util_scripts.add_material:querymat
    - lauenn_maxhkl=lauetoolsnn.util_scripts.add_material:query_hklmax
    - lauenn_pymatgen=lauetoolsnn.util_scripts.add_material:pymatgen_query
    - lauenn_example=lauetoolsnn.util_scripts.add_material:example_scripts
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  number: 0
  
requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
    - numpy >=1.17
  run:
    - python >=3.7
    - matplotlib-base >=3.4.2
    - scipy >=1.7.0
    - numpy >=1.17
    - h5py >=3.1
    - pyqt >=5.9
    - scikit-learn >=0.24.2
    - fabio >=0.11
    - networkx >=2.6.3
    - scikit-image >=0.18
    - tqdm >=4.60
    - keras >=2.7.0
    - tensorflow >=2.7.0

test:
  imports:
    - lauetoolsnn
    - keras
    - scipy
    - numpy
    - h5py
    - tensorflow
    - PyQt5
    - sklearn
    - skimage
    - fabio
    - networkx
    - tqdm
    
about:
  home: https://github.com/BM32ESRF/LaueNN
  summary: LaueNN- neural network training and prediction routine to index single and polycrystalline Laue diffraction patterns
  license: MIT

app:
  entry: lauetoolsnn
  icon: icon.png
  summary:  "Neural network workflow for indexation of Laue patterns"
  type: desk
  
extra:
  recipe-maintainers:
    - ravipurohit1991
