name: Publish_PYPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - uses: actions/setup-python@v2
    - name: Set up Python 3.10
      with:
        python-version: '3.10'
    - name: Install scm version
      run: |
        python -m pip install versiontag
    - name: Install scm version
      run: |
        python -m pip install setuptools-scm==4.1.2
    - name: Install wheel
      run: |
        python -m pip install wheel==0.34.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
